name: ChunkAtlas

description: WIP minecraft map plugin

version: 0.1

main: com.centuryglass.chunk_atlas.serverplugin.Plugin

api-version: 1.14

commands:
    startMapping:
        description: Console only command. If the map thread isn't already running, restart it. 
