/**
 * @file Locator.java
 * 
 * An abstract basis for classes that find Locations using map data.
 */
package com.centuryglass.chunk_atlas.location;

import com.centuryglass.chunk_atlas.worldinfo.ChunkData;
import javax.json.JsonArray;
import org.bukkit.World;

/**
 * Locator classes scan map data for relevant Location objects to categorize.
 */
public abstract class Locator
{
    /**
     * @param region  An optional bukkit World object the Locator can use to
     *                scan for location data.
     */
    public Locator(World region)
    {
        this.region = region;
        locations = new LocationGroup();
    }
    
    /**
     * Gets a JSON array holding all locations found by this Locator.
     * 
     * @return  Location data generated by this Locator.
     */
    public JsonArray getLocationJson()
    {
        return locations.getGroupJSON();
    }
    
    /**
     * Gets this Locator's name.
     * 
     * @return  A String used to represent the Locator. 
     */
    public abstract String getName();
    
    /**
     * Scans a Minecraft map chunk for Locations relevant to this Locator.
     * 
     * @param chunkData  Minecraft chunk data to scan for new Locations.
     */
    public abstract void findChunkLocations(ChunkData chunkData);
    
    /**
     * Performs any necessary Location scanning after scanning all map chunks. 
     */
    public abstract void finalScan();
    
    /**
     * Gets the bukkit World object used to get additional Location data.
     * 
     * @return  The mapped region's World object, or null if not running as a
     *          Minecraft server plugin.
     */
    protected World getRegion()
    {
        return region;
    }
    
    /**
     * Gets the object used by this Locator to store locations.
     * 
     * @return  The Locator's location group object. 
     */
    protected LocationGroup getLocationGroup()
    {
        return locations;
    }
    
    private final LocationGroup locations;
    private final World region;
}
