#include "Biome.h"
#include <map>


// Gets a color value to represent a Minecraft biome.
png::rgb_pixel getBiomeColor(const Biome biome)
{
    static const std::map<Biome, png::rgb_pixel> colorMap =
    {
        { Biome::ocean,
                png::rgb_pixel(0x1a, 0x00, 0xfe) },
        { Biome::deep_ocean,
                png::rgb_pixel(0x16, 0x01, 0x50) },
        { Biome::frozen_ocean,
                png::rgb_pixel(0xc2, 0xbb, 0xff) },
        { Biome::deep_frozen_ocean,
                png::rgb_pixel(0x2a, 0x36, 0x59) },
        { Biome::cold_ocean,
                png::rgb_pixel(0x76, 0x67, 0xff) },
        { Biome::deep_cold_ocean,
                png::rgb_pixel(0x2a, 0x36, 0x59) },
        { Biome::lukewarm_ocean,
                png::rgb_pixel(0x00, 0x81, 0xff) },
        { Biome::deep_lukewarm_ocean,
                png::rgb_pixel(0x00, 0x34, 0x51) },
        { Biome::warm_ocean,
                png::rgb_pixel(0x00, 0xa4, 0xff) },
        { Biome::deep_warm_ocean,
                png::rgb_pixel(0x00, 0x34, 0x51) },
        { Biome::river,
                png::rgb_pixel(0x72, 0x6f, 0xff) },
        { Biome::frozen_river,
                png::rgb_pixel(0xc6, 0xc5, 0xff) },
        { Biome::beach,
                png::rgb_pixel(0x9c, 0x9f, 0x88) },
        { Biome::stone_shore,
                png::rgb_pixel(0x51, 0x53, 0x45) },
        { Biome::snowy_beach,
                png::rgb_pixel(0xe2, 0xe6, 0xc8) },
        { Biome::forest,
                png::rgb_pixel(0x0b, 0xa1, 0x0c) },
        { Biome::wooded_hills,
                png::rgb_pixel(0x0c, 0xb9, 0x03) },
        { Biome::flower_forest,
                png::rgb_pixel(0xfa, 0x93, 0xff) },
        { Biome::birch_forest,
                png::rgb_pixel(0x73, 0xb6, 0x74) },
        { Biome::birch_forest_hills,
                png::rgb_pixel(0x7e, 0xcd, 0x7f) },
        { Biome::tall_birch_forest,
                png::rgb_pixel(0x7b, 0xb8, 0x7c) },
        { Biome::tall_birch_hills,
                png::rgb_pixel(0xa4, 0xe9, 0xa5) },
        { Biome::dark_Forest,
                png::rgb_pixel(0x36, 0x5f, 0x36) },
        { Biome::dark_Forest_hills,
                png::rgb_pixel(0x4a, 0x83, 0x4a) },
        { Biome::jungle,
                png::rgb_pixel(0x00, 0x4a, 0x4a) },
        { Biome::jungle_hills,
                png::rgb_pixel(0x02, 0x62, 0x62) },
        { Biome::modified_jungle,
                png::rgb_pixel(0x16, 0x81, 0x81) },
        { Biome::jungle_edge,
                png::rgb_pixel(0x45, 0x89, 0x7a) },
        { Biome::modified_jungle_edge,
                png::rgb_pixel(0x5c, 0xbf, 0xb7) },
        { Biome::bamboo_jungle,
                png::rgb_pixel(0x9e, 0x96, 0x8d) },
        { Biome::bamboo_jungle_hills,
                png::rgb_pixel(0xbf, 0xb3, 0xa6) },
        { Biome::taiga,
                png::rgb_pixel(0x54, 0x38, 0x36) },
        { Biome::taiga_hills,
                png::rgb_pixel(0x71, 0x4c, 0x49) },
        { Biome::taiga_mountains,
                png::rgb_pixel(0xbd, 0x7d, 0x79) },
        { Biome::snowy_taiga,
                png::rgb_pixel(0x95, 0x89, 0x89) },
        { Biome::snowy_taiga_hills,
                png::rgb_pixel(0xc2, 0xb1, 0xb1) },
        { Biome::snowy_taiga_mountains,
                png::rgb_pixel(0xde, 0xc2, 0xc2) },
        { Biome::giant_tree_taiga,
                png::rgb_pixel(0x40, 0x16, 0x13) },
        { Biome::giant_tree_taiga_hills,
                png::rgb_pixel(0x6c, 0x23, 0x1e) },
        { Biome::giant_spruce_taiga,
                png::rgb_pixel(0x7d, 0x50, 0x46) },
        { Biome::giant_spruce_taiga_hills,
                png::rgb_pixel(0x99, 0x63, 0x56) },
        { Biome::mushroom_fields,
                png::rgb_pixel(0xa1, 0x0b, 0x2c) },
        { Biome::mushroom_fields_shore,
                png::rgb_pixel(0xe2, 0x66, 0x81) },
        { Biome::swamp,
                png::rgb_pixel(0x49, 0x1d, 0x5e) },
        { Biome::swamp_hills,
                png::rgb_pixel(0x86, 0x30, 0xaf) },
        { Biome::savanna,
                png::rgb_pixel(0x90, 0x67, 0x0c) },
        { Biome::savanna_plateau,
                png::rgb_pixel(0xb1, 0x7e, 0x0e) },
        { Biome::shattered_savanna,
                png::rgb_pixel(0xb3, 0x90, 0x42) },
        { Biome::shattered_savanna_plateau,
                png::rgb_pixel(0xf8, 0xcf, 0x75) },
        { Biome::plains,
                png::rgb_pixel(0xb4, 0xff, 0x00) },
        { Biome::sunflower_plains,
                png::rgb_pixel(0xe0, 0xfb, 0x96) },
        { Biome::desert,
                png::rgb_pixel(0xce, 0xbb, 0x00) },
        { Biome::desert_hills,
                png::rgb_pixel(0xff, 0xe8, 0x00) },
        { Biome::desert_lakes,
                png::rgb_pixel(0xfb, 0xf6, 0xc4) },
        { Biome::snowy_tundra,
                png::rgb_pixel(0xae, 0xba, 0xba) },
        { Biome::snowy_mountains,
                png::rgb_pixel(0xcf, 0xea, 0xeb) },
        { Biome::ice_spikes,
                png::rgb_pixel(0x55, 0x6a, 0x6f) },
        { Biome::mountains,
                png::rgb_pixel(0x7e, 0x7a, 0x7a) },
        { Biome::wooded_mountains,
                png::rgb_pixel(0x7e, 0x8a, 0x7e) },
        { Biome::gravelly_mountains,
                png::rgb_pixel(0x5c, 0x63, 0x5c) },
        { Biome::modified_gravelly_mountains,
                png::rgb_pixel(0x42, 0x44, 0x42) },
        { Biome::mountain_edge,
                png::rgb_pixel(0x33, 0x36, 0x33) },
        { Biome::badlands,
                png::rgb_pixel(0xd8, 0x2d, 0x04) },
        { Biome::badlands_plateau,
                png::rgb_pixel(0xe9, 0x5e, 0x42) },
        { Biome::modified_badlands_plateau,
                png::rgb_pixel(0xf7, 0x86, 0x6f) },
        { Biome::wooded_badlands_plateau,
                png::rgb_pixel(0x68, 0x11, 0x00) },
        { Biome::modified_wooded_badlands_plateau,
                png::rgb_pixel(0xbf, 0x22, 0x00) },
        { Biome::eroded_badlands,
                png::rgb_pixel(0x84, 0x1a, 0x00) },
        { Biome::nether,
                png::rgb_pixel(0xff, 0x18, 0x58) },
        { Biome::the_end,
                png::rgb_pixel(0xce, 0xc8, 0xab) },
        { Biome::small_end_islands,
                png::rgb_pixel(0xcd, 0xc2, 0x8e) },
        { Biome::end_midlands,
                png::rgb_pixel(0xb4, 0xab, 0x7f) },
        { Biome::end_highlands,
                png::rgb_pixel(0xf4, 0xf0, 0xda) },
        { Biome::end_barrens,
                png::rgb_pixel(0x91, 0x90, 0x8a) },
        { Biome::the_void,
                png::rgb_pixel(0x00, 0x00, 0x00) },
    };
    try
    {
        return colorMap.at(biome);
    }
    catch (const std::out_of_range& e)
    {
        std::cerr << "No color provided for biome " << (int) biome << "\n";
        return png::rgb_pixel(0, 0, 0);
    }
}
